function validation = test_global_joint_common_shape_rank_sweep()
%TEST_GLOBAL_JOINT_COMMON_SHAPE_RANK_SWEEP Noiseless rank-3 regression test.
    validation = global_joint_common_shape_rank_sweep([], 5, ...
        'SyntheticTestOnly', true, ...
        'NumStarts', 20, ...
        'MaxIter', 1000, ...
        'Tol', 1e-10, ...
        'RandomSeed', 0);
    assert(validation.ran);
    assert(validation.passed);
    expected = [9/14; 13/14; 1; 1; 1];
    assert(max(abs(validation.observed_explained_fraction(:) - expected)) < 1e-12);
    assert(all(diff(validation.observed_explained_fraction) >= -1e-12));
    assert(all(validation.observed_relative_residual(3:5) < 1e-10));
    assert(validation.rank1_legacy_consistent);
    assert(validation.rank1_objective_difference <= ...
        validation.rank1_objective_tolerance);
end
