function result = test_global_joint_svd_analysis_joint_cp_rank1()
%TEST_GLOBAL_JOINT_SVD_ANALYSIS_JOINT_CP_RANK1 Exact noiseless regression test.
    result = global_joint_svd_analysis_joint_cp_rank1([], 3, ...
        'SyntheticTestOnly', true, ...
        'NumStarts', 20, ...
        'MaxIter', 1000, ...
        'Tol', 1e-10, ...
        'RandomSeed', 0, ...
        'DisplayFullArrays', false);
    assert(result.passed);
    assert(result.relative_error < 1e-10);
end
